import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import Comment from "./components/comment";
import { Links } from "./components/links";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" suppressHydrationWarning>
      <body className={inter.className}>
        <div className="p-8">
          <Links></Links>
          {children}
        </div>
      </body>
    </html>
  );
}
